### ISSUE TITLE
4.0.0本地启动报错

### ISSUE THREAD

**Issue by fzlinjianhui** [201206030/novel-plus#124]
The bean 'dataSource', defined in class path resource [io/shardingsphere/shardingjdbc/spring/boot/SpringBootConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class] and overriding is disabled.

如果我在配置文件加上spring.main.allow-bean-definition-overriding=true 这个配置，会报另外一个错误：
Error starting Tomcat context. Exception: org.springframework.beans.factory.BeanCreationException. Message: Error creating bean with name 'com.java2nb.novel.core.listener.StarterListener': Cannot create inner bean '(inner bean)#72f8ae0c' of type [com.java2nb.novel.core.listener.StarterListener] while setting bean property 'listener'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name '(inner bean)#72f8ae0c' defined in file [D:\projects\novel-plus-4.0.0\novel-front\target\classes\com\java2nb\novel\core\listener\StarterListener.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'websiteInfoMapper' defined in file [D:\projects\novel-plus-4.0.0\novel-common\target\classes\com\java2nb\novel\mapper\WebsiteInfoMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.class]: Unsatisfied dependency expressed through method 'sqlSessionFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'io.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration': Initialization of bean failed; nested exception is java.lang.NullPointerException

**Comment by fzlinjianhui** [comment]
如果我直接下载你发版的4.0.0的包，直接启动就没问题，我用源码在idea里面启动就是会报这样的错误，如果我自己打包出来的，也是会报错，我凌乱了，我的jdk版本是：jdk1.8.0_111

**Comment by 201206030** [comment]
这个就是我打包出来的，我已经帮几个同学使用源码装了4.0.0，也没有问题呀



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: JianHui_Lin ***@***.***&gt;
发送时间: 2023年4月17日 10:33
收件人: 201206030/novel-plus ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [201206030/novel-plus] 4.0.0本地启动报错 (Issue #124)





 
如果我直接下载你发版的4.0.0的包，直接启动就没问题，我用源码在idea里面启动就是会报这样的错误，如果我自己打包出来的，也是会报错，我凌乱了，我的jdk版本是：jdk1.8.0_111

**Comment by fzlinjianhui** [comment]
那真的好诡异，我已经折腾好久好久了，就是会报错，要不你也帮我看看，留个联系方式~

**Comment by 201206030** [comment]
> 那真的好诡异，我已经折腾好久好久了，就是会报错，要不你也帮我看看，留个联系方式~

https://novel.xxyopen.com/service.htm 官网上有我的联系方式哦

**Comment by shican1234** [comment]
我是本地启动没有问题 我无论是自己打包 还是直接下载开发者打出来的包   在服务器上运行 都是这个错rror starting Tomcat context. Exception: org.springframework.beans.factory.BeanCreationException. Message: Error creating bean with name 'com.java2nb.novel.core.listener.StarterListener': Cannot create inner bean '(inner bean)#72f8ae0c' of type [com.java2nb.novel.core.listener.StarterListener] while setting bean property 'listener'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name '(inner bean)#72f8ae0c' defined in file [D:\projects\novel-plus-4.0.0\novel-front\target\classes\com\java2nb\novel\core\listener\StarterListener.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'websiteInfoMapper' defined in file [D:\projects\novel-plus-4.0.0\novel-common\target\classes\com\java2nb\novel\mapper\WebsiteInfoMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.class]: Unsatisfied dependency expressed through method 'sqlSessionFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'io.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration': Initialization of bean failed; nested exception is java.lang.NullPointerException

**Comment by 201206030** [comment]
那个问题已经解决了，是配置文件修改错了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: shican1234 ***@***.***&gt;
发送时间: 2023年4月20日 17:53
收件人: 201206030/novel-plus ***@***.***&gt;
抄送: xxy ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [201206030/novel-plus] 4.0.0本地启动报错 (Issue #124)





 
我是本地启动没有问题 我无论是自己打包 还是直接下载开发者打出来的包   在服务器上运行 都是这个错rror starting Tomcat context. Exception: org.springframework.beans.factory.BeanCreationException. Message: Error creating bean with name 'com.java2nb.novel.core.listener.StarterListener': Cannot create inner bean '(inner bean)#72f8ae0c' of type [com.java2nb.novel.core.listener.StarterListener] while setting bean property 'listener'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name '(inner bean)#72f8ae0c' defined in file [D:\projects\novel-plus-4.0.0\novel-front\target\classes\com\java2nb\novel\core\listener\StarterListener.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'websiteInfoMapper' defined in file [D:\projects\novel-plus-4.0.0\novel-common\target\classes\com\java2nb\novel\mapper\WebsiteInfoMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.class]: Unsatisfied dependency expressed through method 'sqlSessionFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'io.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration': Initialization of bean failed; nested exception is java.lang.NullPointerException

**Comment by shican1234** [comment]
我是4.1版本的  启动rg.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'monthIncomeStaSchedule' defined in URL [jar:file:/www/wwwroot/novel-plus/novel-front/novel-front.jar!/BOOT-INF/classes!/com/java2nb/novel/core/schedule/MonthIncomeStaSchedule.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'bookServiceImpl' defined in URL [jar:file:/www/wwwroot/novel-plus/novel-front/novel-front.jar!/BOOT-INF/classes!/com/java2nb/novel/service/impl/BookServiceImpl.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.java2nb.novel.service.impl.BookServiceImpl]: Constructor threw exception; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1341)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1187)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:845)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
	at com.java2nb.novel.FrontNovelApplication.main(FrontNovelApplication.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'bookServiceImpl' defined in URL [jar:file:/www/wwwroot/novel-plus/novel-front/novel-front.jar!/BOOT-INF/classes!/com/java2nb/novel/service/impl/BookServiceImpl.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.java2nb.novel.service.impl.BookServiceImpl]: Constructor threw exception; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:304)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:285)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1341)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1187)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1251)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1171)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760)
	... 27 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.java2nb.novel.service.impl.BookServiceImpl]: Constructor threw exception; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:184)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:300)
	... 41 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: null
	at com.java2nb.novel.service.impl.BookServiceImpl.<init>(BookServiceImpl.java:92)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:172)
	... 43 common frames omitted
Caused by: java.lang.NullPointerException: null
	at io.github.xxyopen.util.IdWorker.getDatacenterId(IdWorker.java:139)
	at io.github.xxyopen.util.IdWorker.<init>(IdWorker.java:61)
	at io.github.xxyopen.util.IdWorker.<clinit>(IdWorker.java:29)
	... 49 common frames omitted
