### ISSUE TITLE
novel_crawl报错：503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by HelloNick666** [201206030/novel-plus#52]
作者你好，非常感谢你的无私开源，好人一生平安。
目前爬虫程序运行有点问题。
1.我把几个爬虫源关掉了，爬虫继续运行。这种情况下，程序是否是在补齐数据库书的章节，而没有爬取新书？开了3个爬虫程序，补齐已有书的章节非常的慢，一天不超过100章。
2.爬虫程序一直报错，日志如下，请问下是否是因为爬虫的频率过高导致的？怎么调整爬取频率？配置文件里好像没有看到，目前是写死的吗？在那个java类里面？
org.springframework.web.client.HttpServerErrorException$ServiceUnavailable: 503 Service Temporarily Unavailable
	at org.springframework.web.client.HttpServerErrorException.create(HttpServerErrorException.java:85)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:124)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:102)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:778)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:736)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:670)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:579)
	at com.java2nb.novel.core.utils.HttpUtil.getByHttpClientWithChrome(HttpUtil.java:35)
	at com.java2nb.novel.core.crawl.CrawlParser.getByHttpClientWithChrome(CrawlParser.java:313)
	at com.java2nb.novel.core.crawl.CrawlParser.parseBookIndexAndContent(CrawlParser.java:216)
	at com.java2nb.novel.core.listener.StarterListener.lambda$contextInitialized$0(StarterListener.java:69)
	at java.lang.Thread.run(Thread.java:748)

**Comment by 201206030** [comment]
其实最好的解决方案是换一个没其他人用的源，因为现在用的人非常多，即使你把频率调到每秒一次请求，可能效果也不会很好，而每秒一次请求已经算很慢的频率了，一本书大概几千请求，这样算下去一本书爬下来最少也得几十分钟，所以我才没有开放爬虫频率的开关，因为从根本上解决不了问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月9日(周五) 上午10:36
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [201206030/novel-plus] novel_crawl报错：503 Service Temporarily Unavailable (#52)




 
作者你好，非常感谢你的无私开源，好人一生平安。
 目前爬虫程序运行有点问题。
 1.我把几个爬虫源关掉了，爬虫继续运行。这种情况下，程序是否是在补齐数据库书的章节，而没有爬取新书？开了3个爬虫程序，补齐已有书的章节非常的慢，一天不超过100章。
 2.爬虫程序一直报错，日志如下，请问下是否是因为爬虫的频率过高导致的？怎么调整爬取频率？配置文件里好像没有看到，目前是写死的吗？在那个java类里面？
 org.springframework.web.client.HttpServerErrorException$ServiceUnavailable: 503 Service Temporarily Unavailable
 at org.springframework.web.client.HttpServerErrorException.create(HttpServerErrorException.java:85)
 at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:124)
 at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:102)
 at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
 at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:778)
 at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:736)
 at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:670)
 at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:579)
 at com.java2nb.novel.core.utils.HttpUtil.getByHttpClientWithChrome(HttpUtil.java:35)
 at com.java2nb.novel.core.crawl.CrawlParser.getByHttpClientWithChrome(CrawlParser.java:313)
 at com.java2nb.novel.core.crawl.CrawlParser.parseBookIndexAndContent(CrawlParser.java:216)
 at com.java2nb.novel.core.listener.StarterListener.lambda$contextInitialized$0(StarterListener.java:69)
 at java.lang.Thread.run(Thread.java:748)

**Comment by 201206030** [comment]
第一个问题基本是你理解的那样，爬虫速度和网络以及服务器配置有关，建议可以使用多台机器运行爬虫，经过测试，如果服务器配置一般的话，使用个人电脑的效果要好一些



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月9日(周五) 上午10:36
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [201206030/novel-plus] novel_crawl报错：503 Service Temporarily Unavailable (#52)




 
作者你好，非常感谢你的无私开源，好人一生平安。
 目前爬虫程序运行有点问题。
 1.我把几个爬虫源关掉了，爬虫继续运行。这种情况下，程序是否是在补齐数据库书的章节，而没有爬取新书？开了3个爬虫程序，补齐已有书的章节非常的慢，一天不超过100章。
 2.爬虫程序一直报错，日志如下，请问下是否是因为爬虫的频率过高导致的？怎么调整爬取频率？配置文件里好像没有看到，目前是写死的吗？在那个java类里面？
 org.springframework.web.client.HttpServerErrorException$ServiceUnavailable: 503 Service Temporarily Unavailable
 at org.springframework.web.client.HttpServerErrorException.create(HttpServerErrorException.java:85)
 at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:124)
 at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:102)
 at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
 at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:778)
 at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:736)
 at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:670)
 at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:579)
 at com.java2nb.novel.core.utils.HttpUtil.getByHttpClientWithChrome(HttpUtil.java:35)
 at com.java2nb.novel.core.crawl.CrawlParser.getByHttpClientWithChrome(CrawlParser.java:313)
 at com.java2nb.novel.core.crawl.CrawlParser.parseBookIndexAndContent(CrawlParser.java:216)
 at com.java2nb.novel.core.listener.StarterListener.lambda$contextInitialized$0(StarterListener.java:69)
 at java.lang.Thread.run(Thread.java:748)

**Comment by HelloNick666** [comment]
好的，谢谢！
