### ISSUE TITLE
点击开始爬取小说之后出现错误

### ISSUE THREAD

**Issue by meijianyue** [201206030/novel-plus#53]
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at com.java2nb.novel.core.crawl.CrawlParser.parseBookIndexAndContent(CrawlParser.java:219)
	at com.java2nb.novel.service.impl.CrawlServiceImpl.parseBookAndSave(CrawlServiceImpl.java:306)
	at com.java2nb.novel.service.impl.CrawlServiceImpl.parseBookList(CrawlServiceImpl.java:249)
	at com.java2nb.novel.service.impl.CrawlServiceImpl.lambda$openOrCloseCrawl$0(CrawlServiceImpl.java:126)
	at java.lang.Thread.run(Thread.java:748)

String content = contentHtml.substring(contentHtml.indexOf(ruleBean.getContentStart()) + ruleBean.getContentStart().length()); `content = content.substring(0, content.indexOf(ruleBean.getContentEnd()));`

有没有人遇到这种错误，求帮助

**Comment by 201206030** [comment]
你用的这个规则已经失效了，换一个爬虫源



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月23日(周五) 下午5:08
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [201206030/novel-plus] 点击开始爬取小说之后出现错误 (#53)




 
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
 at java.lang.String.substring(String.java:1967)
 at com.java2nb.novel.core.crawl.CrawlParser.parseBookIndexAndContent(CrawlParser.java:219)
 at com.java2nb.novel.service.impl.CrawlServiceImpl.parseBookAndSave(CrawlServiceImpl.java:306)
 at com.java2nb.novel.service.impl.CrawlServiceImpl.parseBookList(CrawlServiceImpl.java:249)
 at com.java2nb.novel.service.impl.CrawlServiceImpl.lambda$openOrCloseCrawl$0(CrawlServiceImpl.java:126)
 at java.lang.Thread.run(Thread.java:748)
 
String content = contentHtml.substring(contentHtml.indexOf(ruleBean.getContentStart()) + ruleBean.getContentStart().length()); content = content.substring(0, content.indexOf(ruleBean.getContentEnd()));
 
有没有人遇到这种错误，求帮助

**Comment by meijianyue** [comment]
> 你用的这个规则已经失效了，换一个爬虫源
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年7月23日(周五) 下午5:08 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [201206030/novel-plus] 点击开始爬取小说之后出现错误 (#53) java.lang.StringIndexOutOfBoundsException: String index out of range: -1 at java.lang.String.substring(String.java:1967) at com.java2nb.novel.core.crawl.CrawlParser.parseBookIndexAndContent(CrawlParser.java:219) at com.java2nb.novel.service.impl.CrawlServiceImpl.parseBookAndSave(CrawlServiceImpl.java:306) at com.java2nb.novel.service.impl.CrawlServiceImpl.parseBookList(CrawlServiceImpl.java:249) at com.java2nb.novel.service.impl.CrawlServiceImpl.lambda$openOrCloseCrawl$0(CrawlServiceImpl.java:126) at java.lang.Thread.run(Thread.java:748) String content = contentHtml.substring(contentHtml.indexOf(ruleBean.getContentStart()) + ruleBean.getContentStart().length()); content = content.substring(0, content.indexOf(ruleBean.getContentEnd())); 有没有人遇到这种错误，求帮助 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

有没有能用的爬虫源，项目本身自带的都不能用，这个是索引越界，其他的都是403  或者500

公众号的新爬虫源我也试了，连接都有问题，爬不了

**Comment by 201206030** [comment]
是么 ，很久没看了，等我有时间再看一下

**Comment by 201206030** [comment]
403之类的可以先用用，开始可能会缺失章节，后面会自动更新补全

**Comment by meijianyue** [comment]
### Error updating database.  Cause: java.sql.SQLException: Field 'pic_url' doesn't have a default value
### The error may involve com.java2nb.novel.mapper.CrawlBookMapper.insert-Inline
### The error occurred while setting parameters
### SQL: insert into book (id, work_direction, cat_id, cat_name, book_name, author_name, book_desc, score, book_status, visit_count, word_count, last_index_id, last_index_name, last_index_update_time, update_time, create_time, crawl_source_id, crawl_book_id, crawl_last_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
### Cause: java.sql.SQLException: Field 'pic_url' doesn't have a default value
; Field 'pic_url' doesn't have a default value; nested exception is java.sql.SQLException: Field 'pic_url' doesn't have a default value



出现了新的问题，这是数据库的问题，还是爬虫的问题？

**Comment by 201206030** [comment]
这个应该是封面图片的规则失效了，我考虑下要不要设置默认图片

**Comment by meijianyue** [comment]
能不能给个能用的爬虫源，我都在公众号付费了，那个复制不了 难受

**Comment by 201206030** [comment]
发给你了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月30日(周五) 中午11:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [201206030/novel-plus] 点击开始爬取小说之后出现错误 (#53)




 
能不能给个能用的爬虫源，我都在公众号付费了，那个复制不了 难受
