### ISSUE TITLE
这个是不是还不可以用？

### ISSUE THREAD

**Issue by chenyaozong528** [201206030/novel-plus#7]
运行起来，趴取报错。

**Comment by chenyaozong528** [comment]
后台的功能也感觉还在开发中

**Comment by 201206030** [comment]
可以用

**Comment by chenyaozong528** [comment]
我发现爬取小说403

**Comment by chenyaozong528** [comment]
org.springframework.web.client.HttpClientErrorException$Forbidden: 403 Forbidden
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:83)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:102)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:778)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:736)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:670)
	at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:338)
	at com.java2nb.novel.core.utils.HttpUtil.getByHttpClient(HttpUtil.java:20)
	at com.java2nb.novel.service.impl.CrawlServiceImpl.parseBookList(CrawlServiceImpl.java:163)
	at com.java2nb.novel.service.impl.CrawlServiceImpl.lambda$openOrCloseCrawl$0(CrawlServiceImpl.java:115)
	at java.lang.Thread.run(Thread.java:748)

**Comment by chenyaozong528** [comment]
书包网有反扒了。这个需要使用代理ip吗？

**Comment by chenyaozong528** [comment]
然后现在代码是不是不支持主动趴取，我看代码只有更新作品

**Comment by 201206030** [comment]
更新作品是自动进行的，你点击运行按钮就是主动爬取

**Comment by chenyaozong528** [comment]
> 更新作品是自动进行的，你点击运行按钮就是主动爬取
不行。报错  getDatacenterId: null
然后书包网403的怎么解决？
